version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    volumes:
      - /media/pi/Data/DataMiningProjekt/mongoDBStuff/data:/data/db
      - /media/pi/Data/DataMiningProjekt/mongoDBStuff:/backup
      - /media/pi/Data/DataMiningProjekt/mongoDBStuff/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - /media/pi/Data/DataMiningProjekt/mongoDBStuff/currentData.json:/docker-entrypoint-initdb.d/currentData.json
      - ./setupDockerMongoDB.sh:/setupDockerMongoDB.sh:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    command: ["/bin/bash", "/setupDockerMongoDB.sh"]
    restart: "always"
    networks:
      - datamining_network

  analyze_html:
    image: fabianstettler/analyze_html_image  # Verweise auf das lokal gebaute Image
    container_name: analyze_html_container
    volumes:
      - /media/pi/Data/DataMiningProjekt:/usr/src/datamining
    depends_on:
      - mongodb
    restart: "no"
    networks:
      - datamining_network

networks:
  datamining_network:
    driver: bridge
